'use strict';
// Format-parity tests over the PG 12…18 matrix corpus: the TEXT, JSON and
// YAML captures of the same EXPLAIN must normalize to the same tree and the
// same planner estimates through the current (text-canonical) pipeline.
// Actual metrics come from three separate executions, so only their
// presence class is compared, never their values.
// Corpus is generated by tools/gen-fixtures.sh and committed.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { PgPlan } = require('./helpers.js');

const MATRIX = path.join(__dirname, 'plans', 'matrix');

// DML shapes execute for real once per format; even under ROLLBACK the
// table's physical size drifts between runs, and the planner extrapolates
// frozen statistics onto the current size — so costs AND row estimates
// move slightly. For those shapes parity covers the tree structure only.
const DML_SHAPES = new Set(['merge', 'triggers', 'wal']);

function skeleton(plan, withEstimates, dropGroupKey) {
  return plan.nodes.map(n => {
    const s = {
      spec: n.spec, type: n.type, relation: n.relation, index: n.index,
      alias: n.alias, parent: n.parent, children: n.children.length,
      planWidth: n.planWidth,
      never: n.never,
      // deterministic semantic fields: identical across formats of one plan
      sortKey: n.sortKey || null,
      groupKey: dropGroupKey ? undefined : n.groupKey || null,
      filters: n.filters.map(f => f.key + ': ' + f.val),
    };
    if (withEstimates) {
      s.costStartup = n.costStartup;
      s.costTotal = n.costTotal;
      s.planRows = n.planRows;
    }
    return s;
  });
}

const dirs = fs.existsSync(MATRIX)
  ? fs.readdirSync(MATRIX).filter(d => /^pg\d+$/.test(d)).sort()
  : [];

test('matrix corpus present', t => {
  if (!dirs.length) t.skip('no matrix fixtures — run tools/gen-fixtures.sh');
});

for (const d of dirs) {
  const dir = path.join(MATRIX, d);
  const shapes = [...new Set(fs.readdirSync(dir)
    .filter(f => /\.(txt|json|yaml)$/.test(f))
    .map(f => f.replace(/\.(txt|json|yaml)$/, '')))].sort();
  for (const shape of shapes) {
    test(`parity ${d}/${shape}`, () => {
      const plans = {};
      for (const ext of ['txt', 'json', 'yaml']) {
        const f = path.join(dir, shape + '.' + ext);
        assert.ok(fs.existsSync(f), 'missing ' + ext + ' variant');
        plans[ext] = PgPlan.parse(fs.readFileSync(f, 'utf8'));
      }
      assert.equal(plans.txt.format, 'text');
      assert.equal(plans.json.format, 'json');
      assert.equal(plans.yaml.format, 'yaml');

      const withEstimates = !DML_SHAPES.has(shape);
      // "Grouping Sets" has no text representation in the JSON/YAML emitter
      // yet; the loss is diagnosed (unsupported_field), so groupKey is
      // excluded from comparison for those plans only
      const dropGroupKey = [plans.json, plans.yaml].some(p =>
        p.diagnostics.some(d => d.code === 'unsupported_field'
          && /Grouping Sets/.test(d.message)));
      const sk = skeleton(plans.txt, withEstimates, dropGroupKey);
      assert.deepEqual(skeleton(plans.json, withEstimates, dropGroupKey), sk, 'json tree != text tree');
      assert.deepEqual(skeleton(plans.yaml, withEstimates, dropGroupKey), sk, 'yaml tree != text tree');

      const hasTimes = p => p.nodes.some(n => n.timeTotal != null);
      assert.equal(hasTimes(plans.json), hasTimes(plans.txt), 'actual-time presence differs (json)');
      assert.equal(hasTimes(plans.yaml), hasTimes(plans.txt), 'actual-time presence differs (yaml)');

      const extKeys = p => new Set(p.ext.map(e => e.key));
      for (const k of ['Execution Time', 'Planning Time', 'Serialization']) {
        assert.equal(extKeys(plans.json).has(k), extKeys(plans.txt).has(k),
          k + ' presence differs (json)');
        assert.equal(extKeys(plans.yaml).has(k), extKeys(plans.txt).has(k),
          k + ' presence differs (yaml)');
      }
      assert.equal(plans.json.triggers.length, plans.txt.triggers.length, 'trigger count (json)');
      assert.equal(plans.yaml.triggers.length, plans.txt.triggers.length, 'trigger count (yaml)');

      // analyzer invariant must hold in every format
      for (const [ext, p] of Object.entries(plans)) {
        const root = p.nodes[0];
        if (root.timeIncl == null) continue;
        const sumExcl = p.nodes.filter(x => !x.spec && x.timeExcl != null)
          .reduce((s, x) => s + x.timeExcl, 0);
        assert.ok(sumExcl <= root.timeIncl * 1.35 + 1,
          `${ext}: sumExcl ${sumExcl.toFixed(3)} > rootIncl ${root.timeIncl.toFixed(3)}`);
      }
    });
  }
}
